<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/OnContractEmployee" xmlns:tns="http://www.example.org/OnContractEmployee" elementFormDefault="qualified">


    <element name="empid" type="string"></element>

    <element name="empname" type="string"></element>

    <element name="salary" type="int"></element>



    <element name="OnContractEmployee" type="tns:OnContractEmployeeType"></element>

    <complexType name="OnContractEmployeeType">
    	<sequence>
    		<element ref="tns:empid"></element>
    		<element ref="tns:empname"></element>
    		<element ref="tns:salary"></element>
    	</sequence>
    </complexType>
</schema>